# Generated by Django 2.2.6 on 2021-01-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201228_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zwiftpower_link',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
