# Generated by Django 2.2.6 on 2020-12-27 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('racetype', models.CharField(choices=[('Race', 'Race'), ('Team time trial', 'Team time trial')], max_length=15)),
                ('date', models.DateField()),
                ('elevation', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=124, null=True)),
                ('division', models.CharField(blank=True, max_length=124, null=True)),
                ('riders', models.IntegerField(blank=True, null=True)),
                ('team_participating', models.IntegerField(blank=True, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.Race')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='race.Team')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='race.Season'),
        ),
        migrations.CreateModel(
            name='RiderResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KOM_points', models.IntegerField(blank=True, default=0, null=True)),
                ('finish_place', models.IntegerField(blank=True, null=True)),
                ('avg_power', models.IntegerField(blank=True, null=True)),
                ('norm_power', models.IntegerField(blank=True, null=True)),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='race.Race')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='race.Team')),
                ('teamresult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='race.RaceResult')),
            ],
            options={
                'unique_together': {('rider', 'race')},
            },
        ),
        migrations.CreateModel(
            name='RaceRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='race.Race')),
            ],
            options={
                'unique_together': {('race', 'participant')},
            },
        ),
    ]
