# Generated by Django 2.2.6 on 2020-12-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='riderresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='riderresult',
            name='race',
        ),
        migrations.RemoveField(
            model_name='riderresult',
            name='rider',
        ),
        migrations.RemoveField(
            model_name='riderresult',
            name='team',
        ),
        migrations.RemoveField(
            model_name='riderresult',
            name='teamresult',
        ),
        migrations.DeleteModel(
            name='RaceResult',
        ),
        migrations.DeleteModel(
            name='RiderResult',
        ),
    ]
