# Generated by Django 2.2.6 on 2020-12-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_auto_20201228_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='zwiftinsider_route_link',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
