# Generated by Django 2.2.6 on 2021-01-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_race_zwiftinsider_route_link'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='race',
            unique_together={('number', 'season')},
        ),
    ]
